### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by Mpompili** [Mpompili/vibesky#3]
- [x]  Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
Hey @Mpompili , great work on this MVP! The functionality is complete. I can log in and out, and sign up. The demo user feature is good too. Additionally, errors both render and clear at the right times.

Update the following small items to complete this MVP!
- [x] Remove reference to "Sound Cloud in the terms / logo". You can replace the logo with Vibesky.
- [x] Render errors with a little more space/ color red, like so:
```css
#session-error-message {
     width: 100%;
     list-style: none;
     color: red;
     padding-bottom: 10px;
}
```

I would also make the `session-form-box` height: 500px instead of 570px to better wrap the content.
